export const googleFonts = [
    { label: "Roboto", value: "Roboto" },
    { label: "Open Sans", value: "Open Sans" },
    { label: "Lato", value: "Lato" },
    { label: "Montserrat", value: "Montserrat" },
    { label: "Oswald", value: "Oswald" },
    { label: "Source Sans Pro", value: "Source Sans Pro" },
    { label: "Poppins", value: "Poppins" },
    { label: "Merriweather", value: "Merriweather" },
    { label: "Nunito", value: "Nunito" },
    { label: "Ubuntu", value: "Ubuntu" },
    { label: "Raleway", value: "Raleway" },
    { label: "PT Sans", value: "PT Sans" },
    { label: "Noto Sans", value: "Noto Sans" },
    { label: "Roboto Condensed", value: "Roboto Condensed" },
    { label: "Playfair Display", value: "Playfair Display" },
    { label: "Quicksand", value: "Quicksand" },
    { label: "Work Sans", value: "Work Sans" },
    { label: "Mukta", value: "Mukta" },
    { label: "Arimo", value: "Arimo" },
    { label: "Cairo", value: "Cairo" },
    { label: "Fira Sans", value: "Fira Sans" },
    { label: "Libre Franklin", value: "Libre Franklin" },
    { label: "Bebas Neue", value: "Bebas Neue" },
    { label: "Rubik", value: "Rubik" },
    { label: "Titillium Web", value: "Titillium Web" },
    { label: "Indie Flower", value: "Indie Flower" },
    { label: "Anton", value: "Anton" },
    { label: "Varela Round", value: "Varela Round" },
    { label: "Josefin Sans", value: "Josefin Sans" },
    { label: "Barlow", value: "Barlow" },
    { label: "Tajawal", value: "Tajawal" },
    { label: "Signika", value: "Signika" },
    { label: "Dancing Script", value: "Dancing Script" },
    { label: "DM Sans", value: "DM Sans" },
    { label: "Cabin", value: "Cabin" },
    { label: "Manrope", value: "Manrope" },
    { label: "Prompt", value: "Prompt" },
    { label: "Karla", value: "Karla" },
    { label: "Overpass", value: "Overpass" },
    { label: "Lora", value: "Lora" },
    { label: "Muli", value: "Muli" },
    { label: "Heebo", value: "Heebo" },
    { label: "Exo 2", value: "Exo 2" },
    { label: "Asap", value: "Asap" },
    { label: "IBM Plex Sans", value: "IBM Plex Sans" },
    { label: "Abel", value: "Abel" },
    { label: "Zilla Slab", value: "Zilla Slab" },
    { label: "Comfortaa", value: "Comfortaa" },
    { label: "Patua One", value: "Patua One" },
    { label: "Bitter", value: "Bitter" },
  ];
  