import { heroIcons } from "./icons";

export const sectionConfig = [
  {
    name: "Hero Lead",
    id: "hero-lead",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "logoSrc",
        type: "file",
        label: "Logo",
        value: null,
      },
      {
        name: "backgroundImgSrc",
        type: "file",
        label: "Imagem de Fundo",
        value: null,
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo da seção",
        value: "#f6f6f6",
      },
      {
        name: "titleText",
        type: "text",
        label: "Texto",
        value: "Título",
      },
      {
        name: "titleFont",
        type: "font",
        label: "Fonte do Título",
        value: "Roboto",
      },
      {
        name: "titleColor",
        type: "color",
        label: "Cor do Título",
        value: "#121212",
      },
      {
        name: "subtitleText",
        type: "text",
        label: "Texto",
        value: "Subtítulo",
      },
      {
        name: "subtitleFont",
        type: "font",
        label: "Fonte do Subtítulo",
        value: "Poppins",
      },
      {
        name: "subtitleColor",
        type: "color",
        label: "Cor do Subtítulo",
        value: "#121212",
      },
      {
        name: "formPlaceholderName",
        type: "text",
        label: "Placeholder Nome",
        value: "Nome",
      },
      {
        name: "formPlaceholderPhone",
        type: "text",
        label: "Placeholder Telefone",
        value: "Telefone",
      },
      {
        name: "formPlaceholderEmail",
        type: "text",
        label: "Placeholder E-mail",
        value: "E-mail",
      },
      {
        name: "formTextColor",
        type: "color",
        label: "Cor do Texto do Formulário",
        value: "#121212",
      },
      {
        name: "buttonText",
        type: "text",
        label: "Texto do Botão",
        value: "Clique aqui",
      },
      {
        name: "buttonColor",
        type: "color",
        label: "Cor do Botão",
        value: "#3B82F6",
      },
      {
        name: "buttonTextColor",
        type: "color",
        label: "Cor do Texto do Botão",
        value: "#fff",
      },
      {
        name: "buttonLink",
        type: "text",
        label: "Link do Botão",
        value: "#",
      },
    ],
  },
  {
    name: "Hero",
    id: "hero",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "titleText",
        type: "text",
        label: "Texto do Título",
        value: "Título",
      },
      {
        name: "titleFont",
        type: "font",
        label: "Fonte do Título",
        value: "Roboto",
      },
      {
        name: "titleColor",
        type: "color",
        label: "Cor do Título",
        value: "#121212",
      },
      {
        name: "subtitleText",
        type: "text",
        label: "Texto do Subtítulo",
        value: "Subtítulo",
      },
      {
        name: "subtitleFont",
        type: "font",
        label: "Fonte do Subtítulo",
        value: "Poppins",
      },
      {
        name: "subtitleColor",
        type: "color",
        label: "Cor do Subtítulo",
        value: "#121212",
      },
      {
        name: "contentText",
        type: "content",
        label: "Texto do Conteúdo",
        value:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae enim eget eros gravida tempor. Sed vitae vulputate odio. Quisque malesuada libero in placerat suscipit. Morbi semper mi libero, a ultricies enim pellentesque et. Sed et pulvinar metus. Donec in dignissim eros. Fusce dignissim tellus vitae sapien viverra, eu porttitor tortor dignissim.",
      },
      {
        name: "contentFont",
        type: "font",
        label: "Fonte do Conteúdo",
        value: "Poppins",
      },
      {
        name: "contentColor",
        type: "color",
        label: "Cor do Conteúdo",
        value: "#121212",
      },
      {
        name: "buttonText",
        type: "text",
        label: "Texto do Botão",
        value: "Clique aqui",
      },
      {
        name: "buttonColor",
        type: "color",
        label: "Cor do Botão",
        value: "#3B82F6",
      },
      {
        name: "buttonTextColor",
        type: "color",
        label: "Cor do Texto do Botão",
        value: "#fff",
      },
      {
        name: "buttonLink",
        type: "text",
        label: "Link do Botão",
        value: "#",
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo da seção",
        value: "#fff",
      },
      {
        name: "overlayImgSrc",
        type: "file",
        label: "Imagem de Destaque",
        value: null,
      },
    ],
  },
  {
    name: "Ícones",
    id: "icons",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "titleText",
        type: "text",
        label: "Texto do Título",
        value: "Título",
      },
      {
        name: "titleFont",
        type: "font",
        label: "Fonte do Título",
        value: "Roboto",
      },
      {
        name: "titleColor",
        type: "color",
        label: "Cor do Título",
        value: "text-black",
      },
      {
        name: "subtitleText",
        type: "text",
        label: "Texto do Subtítulo",
        value: "Subtítulo",
      },
      {
        name: "subtitleFont",
        type: "font",
        label: "Fonte do Subtítulo",
        value: "Poppins",
      },
      {
        name: "subtitleColor",
        type: "color",
        label: "Cor do Subtítulo",
        value: "#121212",
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo da seção",
        value: "#f6f6f6",
      },
      {
        name: "iconColor",
        type: "color",
        label: "Cor dos ícones",
        value: "#fff",
      },
      {
        name: "iconBackgroundColor",
        type: "color",
        label: "Cor de Fundo dos ícones",
        value: "#3B82F6",
      },
      {
        name: "iconTextFont",
        type: "font",
        label: "Fonte dos textos",
        value: "Roboto",
      },
      {
        name: "iconTitleColor",
        type: "color",
        label: "Cor do Título do Ícone",
        value: "#121212",
      },
      {
        name: "iconSubtitleColor",
        type: "color",
        label: "Cor do Subtítulo do Ícone",
        value: "#121212",
      },
      {
        name: "icons",
        type: "list",
        label: "Lista de Ícones",
        value: [
          {
            icon: heroIcons.filter((option) => option.value === "staricon")[0].label,
            iconTitle: "Título",
            iconSubtitle: "Subtítulo",
          },
        ],
        fields: [
          {
            name: "icon",
            type: "text",
            label: "Ícone",
            value: heroIcons.filter((option) => option.value === "staricon"),
          },
          {
            name: "iconTitle",
            type: "text",
            label: "Título",
          },
          {
            name: "iconSubtitle",
            type: "text",
            label: "Subtítulo do Ícone",
            value: "Subtítulo",
          },
        ],
      },
    ],
  },
  {
    name: "Vídeo",
    id: "video",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "videoUrl",
        type: "text",
        label: "URL do Vídeo",
        value:
          "https://www.youtube.com/watch?v=u31qwQUeGuM&ab_channel=JoomlaTemplate",
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo",
        value: "#fff",
      },
      {
        name: "backgroundImgSrc",
        type: "file",
        label: "Imagem de Fundo",
        value: null,
      },
    ],
  },
  {
    name: "Mapa",
    id: "map",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo da Seção",
        value: "#f6f6f6",
      },
      {
        name: "titleText",
        type: "text",
        label: "Texto do Título",
        value: "Título",
      },
      {
        name: "titleFont",
        type: "font",
        label: "Fonte do Título",
        value: "Roboto",
      },
      {
        name: "titleColor",
        type: "color",
        label: "Cor do Título",
        value: "#121212",
      },
      {
        name: "contentText",
        type: "content",
        label: "Texto do Conteúdo",
        value:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae enim eget eros gravida tempor. Sed vitae vulputate odio. Quisque malesuada libero in placerat suscipit. Morbi semper mi libero, a ultricies enim pellentesque et. Sed et pulvinar metus. Donec in dignissim eros. Fusce dignissim tellus vitae sapien viverra, eu porttitor tortor dignissim.",
      },
      {
        name: "contentFont",
        type: "font",
        label: "Fonte do Conteúdo",
        value: "Poppins",
      },
      {
        name: "contentColor",
        type: "color",
        label: "Cor do Conteúdo",
        value: "#121212",
      },
      {
        name: "mapTitleText",
        type: "text",
        label: "Texto do Título do Mapa",
        value: "",
      },
      {
        name: "mapTitleFont",
        type: "font",
        label: "Fonte do Título do Mapa",
        value: "Roboto",
      },
      {
        name: "mapTitleColor",
        type: "color",
        label: "Cor do Título do Mapa",
        value: "#121212",
      },
      {
        name: "mapSubtitleText",
        type: "content",
        label: "Texto do Subtítulo do Mapa",
        value: "",
      },
      {
        name: "mapSubtitleFont",
        type: "font",
        label: "Fonte do Subtítulo do Mapa",
        value: "Poppins",
      },
      {
        name: "mapSubtitleColor",
        type: "color",
        label: "Cor do Subtítulo do Mapa",
        value: "#121212",
      },
      {
        name: "mapEmbedUrl",
        type: "text",
        label: "Iframe do Mapa",
        value:
          '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d120024.2159309127!2d-44.01658220536745!3d-19.934652968996662!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xa690cacacf2c33%3A0x5b35795e3ad23997!2sBelo%20Horizonte%2C%20MG!5e0!3m2!1spt-BR!2sbr!4v1732815896584!5m2!1spt-BR!2sbr" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
      },
    ],
  },
  {
    name: "Footer",
    id: "footer",
    fields: [
      {
        name: "show",
        type: "checkbox",
        label: "Exibir seção",
        value: true,
      },
      {
        name: "logoSrc",
        type: "file",
        label: "Logo",
        value: null,
      },
      {
        name: "sectionBackgroundColor",
        type: "color",
        label: "Cor de Fundo da Seção",
        value: "#fff",
      },

      {
        name: "email",
        type: "text",
        label: "E-mail",
        value: "email@email.com",
      },
      {
        name: "whatsappLink",
        type: "text",
        label: "Link do WhatsApp",
        value: "",
      },
      {
        name: "instagramLink",
        type: "text",
        label: "Link do Instagram",
        value: "",
      },
      {
        name: "iconTextColor",
        type: "color",
        label: "Cor dos Ícones",
        value: "#121212",
      },
    ],
  },
];
